// Login Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Register Action Types
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Verify Action Types
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';

// Resedn Code Action Types
export const RESEND_CODE_REQUEST = 'RESEND_CODE_REQUEST';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const RESEND_CODE_FAILURE = 'RESEND_CODE_FAILURE';

// Consult Order Types
export const CONSULT_ORDER_REQUEST = 'CONSULT_ORDER_REQUEST';
export const CONSULT_ORDER_SUCCESS = 'CONSULT_ORDER_SUCCESS';
export const CONSULT_ORDER_FAILURE = 'CONSULT_ORDER_FAILURE';

export const CONSULT_ORDER_FETCH = 'CONSULT_ORDER_FETCH';
export const CONSULT_ORDER_POST = 'CONSULT_ORDER_POST';
export const CONSULT_ORDER_FETCH_FAILURE = 'CONSULT_ORDER_FETCH_FAILURE';



// Special Order Types
export const SPECIAL_ORDER_REQUEST = 'SPECIAL_ORDER_REQUEST';
export const SPECIAL_ORDER_SUCCESS = 'SPECIAL_ORDER_SUCCESS';
export const SPECIAL_ORDER_FAILURE = 'SPECIAL_ORDER_FAILURE';

export const SPECIAL_ORDER_FETCH = 'SPECIAL_ORDER_FETCH';
export const SPECIAL_ORDER_POST = 'SPECIAL_ORDER_POST';
export const SPECIAL_ORDER_FETCH_FAILURE = 'SPECIAL_ORDER_FETCH_FAILURE';

// Contract Order Types
export const CONTRACT_ORDER_REQUEST = 'CONTRACT_ORDER_REQUEST';
export const CONTRACT_ORDER_SUCCESS = 'CONTRACT_ORDER_SUCCESS';
export const CONTRACT_ORDER_FAILURE = 'CONTRACT_ORDER_FAILURE';

export const CONTRACT_ORDER_FETCH = 'CONTRACT_ORDER_FETCH';
export const CONTRACT_ORDER_POST = 'CONTRACT_ORDER_POST';
export const CONTRACT_ORDER_FETCH_FAILURE = 'CONTRACT_ORDER_FETCH_FAILURE';




